name: sm_public_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.15
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  intl: ^0.20.1
  path_provider: ^2.1.0
  pdf: ^3.10.8 # Latest version for creating PDFs
  printing: ^5.12.0 # For saving and printing the PDF
  permission_handler: ^11.3.1
  google_fonts: ^6.2.1
  animate_do: ^3.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/dashboard/
