// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Zmi_tf9Shogp2JWt4yVbZrssVvreICw',
    appId: '1:546093121597:web:56938cd83afc2041006a54',
    messagingSenderId: '546093121597',
    projectId: 'sm-public-app',
    authDomain: 'sm-public-app.firebaseapp.com',
    storageBucket: 'sm-public-app.firebasestorage.app',
    measurementId: 'G-GDB9LCSVCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD81IppBBwVNWoaC7rSo1a9bob_0Kgpo2s',
    appId: '1:546093121597:android:e6a2148f092d7a66006a54',
    messagingSenderId: '546093121597',
    projectId: 'sm-public-app',
    storageBucket: 'sm-public-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChLMeUmJFPdIrh1H5951h7HK2zMnAA8LE',
    appId: '1:546093121597:ios:a617c342702374be006a54',
    messagingSenderId: '546093121597',
    projectId: 'sm-public-app',
    storageBucket: 'sm-public-app.firebasestorage.app',
    iosBundleId: 'com.example.smPublicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChLMeUmJFPdIrh1H5951h7HK2zMnAA8LE',
    appId: '1:546093121597:ios:a617c342702374be006a54',
    messagingSenderId: '546093121597',
    projectId: 'sm-public-app',
    storageBucket: 'sm-public-app.firebasestorage.app',
    iosBundleId: 'com.example.smPublicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4Zmi_tf9Shogp2JWt4yVbZrssVvreICw',
    appId: '1:546093121597:web:9747d4f97d50d3a4006a54',
    messagingSenderId: '546093121597',
    projectId: 'sm-public-app',
    authDomain: 'sm-public-app.firebaseapp.com',
    storageBucket: 'sm-public-app.firebasestorage.app',
    measurementId: 'G-N1SQB9NDBM',
  );

}